// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9rvoeiwlfPO7wzY9lLGI7LJ_cKKaUQRA',
    appId: '1:316724211138:web:d1bf26eebbf19100c6fa5b',
    messagingSenderId: '316724211138',
    projectId: 'tanoramirayhina',
    authDomain: 'tanoramirayhina.firebaseapp.com',
    storageBucket: 'tanoramirayhina.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUL6Qh89HXQluWj1nJaGYon3cw7_Dzxrc',
    appId: '1:316724211138:android:a8fbf69605962993c6fa5b',
    messagingSenderId: '316724211138',
    projectId: 'tanoramirayhina',
    storageBucket: 'tanoramirayhina.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqn58AFOaKvMTLEEvCM39qcHXuBDlGFhM',
    appId: '1:316724211138:ios:7d6e32466e7cd15ec6fa5b',
    messagingSenderId: '316724211138',
    projectId: 'tanoramirayhina',
    storageBucket: 'tanoramirayhina.appspot.com',
    iosClientId: '316724211138-omqupmktvkbfjbbaunhtep7eeojumokv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tanoramirayhina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqn58AFOaKvMTLEEvCM39qcHXuBDlGFhM',
    appId: '1:316724211138:ios:7d6e32466e7cd15ec6fa5b',
    messagingSenderId: '316724211138',
    projectId: 'tanoramirayhina',
    storageBucket: 'tanoramirayhina.appspot.com',
    iosClientId: '316724211138-omqupmktvkbfjbbaunhtep7eeojumokv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tanoramirayhina',
  );
}
